version: '3.9'

services:
  credit-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: credit-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=credit
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://credit-db:3306/credit_db
      - SPRING_DATASOURCE_USERNAME=credit_user
      - SPRING_DATASOURCE_PASSWORD=credit_password
      - SERVER_PORT=8080
    networks:
      - credit-network
    depends_on:
      credit-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  credit-db:
    image: mysql:8.0
    container_name: credit-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: credit_db
      MYSQL_USER: credit_user
      MYSQL_PASSWORD: credit_password
    ports:
      - "3306:3306"
    volumes:
      - credit-db-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - credit-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "credit_user", "-p$$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: credit-db
      MYSQL_ROOT_PASSWORD: credit_password
    networks:
      - credit-network
    depends_on:
      - credit-db


volumes:
  credit-db-data:

networks:
  credit-network:
    driver: bridge
